class AddColumnPrises < ActiveRecord::Migration[6.0]
  def change
    add_column :prises, :video_p, :text
    add_column :prises, :img_p1, :text
    add_column :prises, :img_p2, :text
    add_column :prises, :img_p3, :text
    add_column :prises, :img_p4, :text
    add_column :prises, :img_p5, :text
    add_column :prises, :legend_p1, :text
    add_column :prises, :legend_p2, :text
    add_column :prises, :legend_p3, :text
    add_column :prises, :legend_p4, :text
    add_column :prises, :legend_p5, :text
    add_column :prises, :avatar_img_p1, :text
    add_column :prises, :avatar_img_p2, :text
    add_column :prises, :avatar_img_p3, :text
    add_column :prises, :avatar_img_p4, :text
    add_column :prises, :avatar_img_p5, :text
    add_column :prises, :avatar_img_p6, :text
    add_column :prises, :avatar_img_p7, :text
    add_column :prises, :avatar_img_p8, :text
    add_column :prises, :avatar_img_p9, :text
    add_column :prises, :avatar_img_p10, :text
    add_column :prises, :avatar_name_p1, :text
    add_column :prises, :avatar_name_p2, :text
    add_column :prises, :avatar_name_p3, :text
    add_column :prises, :avatar_name_p4, :text
    add_column :prises, :avatar_name_p5, :text
    add_column :prises, :avatar_name_p6, :text
    add_column :prises, :avatar_name_p7, :text
    add_column :prises, :avatar_name_p8, :text
    add_column :prises, :avatar_name_p9, :text
    add_column :prises, :avatar_name_p10, :text
    add_column :prises, :avatar_url_p1, :text
    add_column :prises, :avatar_url_p2, :text
    add_column :prises, :avatar_url_p3, :text
    add_column :prises, :avatar_url_p4, :text
    add_column :prises, :avatar_url_p5, :text
    add_column :prises, :avatar_url_p6, :text
    add_column :prises, :avatar_url_p7, :text
    add_column :prises, :avatar_url_p8, :text
    add_column :prises, :avatar_url_p9, :text
    add_column :prises, :avatar_url_p10, :text
    add_column :prises, :avatar_titre_p1, :text
    add_column :prises, :avatar_titre_p2, :text
    add_column :prises, :avatar_titre_p3, :text
    add_column :prises, :avatar_titre_p4, :text
    add_column :prises, :avatar_titre_p5, :text
    add_column :prises, :avatar_titre_p6, :text
    add_column :prises, :avatar_titre_p7, :text
    add_column :prises, :avatar_titre_p8, :text
    add_column :prises, :avatar_titre_p9, :text
    add_column :prises, :avatar_titre_p10, :text
    add_column :prises, :introduction_p1, :text
    add_column :prises, :paraph_p1, :text
    add_column :prises, :paraph_p2, :text
    add_column :prises, :paraph_p3, :text
    add_column :prises, :paraph_p4, :text
    add_column :prises, :titre_p, :text
    add_column :prises, :sous_titre_p, :text
    add_column :prises, :date_p, :text
    add_column :prises, :lieu_p, :text
    add_column :prises, :lien_url1_p, :text
    add_column :prises, :lien_url2_p, :text
  end
end
