class AddContentToMentorats < ActiveRecord::Migration[6.0]
  def change
        add_column :mentorats, :video_m, :text
    add_column :mentorats, :img_m1, :text
    add_column :mentorats, :img_m2, :text
    add_column :mentorats, :img_m3, :text
    add_column :mentorats, :img_m4, :text
    add_column :mentorats, :img_m5, :text
    add_column :mentorats, :legend_m1, :text
    add_column :mentorats, :legend_m2, :text
    add_column :mentorats, :legend_m3, :text
    add_column :mentorats, :legend_m4, :text
    add_column :mentorats, :legend_m5, :text
    add_column :mentorats, :avatar_img_m1, :text
    add_column :mentorats, :avatar_img_m2, :text
    add_column :mentorats, :avatar_img_m3, :text
    add_column :mentorats, :avatar_img_m4, :text
    add_column :mentorats, :avatar_img_m5, :text
    add_column :mentorats, :avatar_img_m6, :text
    add_column :mentorats, :avatar_img_m7, :text
    add_column :mentorats, :avatar_img_m8, :text
    add_column :mentorats, :avatar_img_m9, :text
    add_column :mentorats, :avatar_img_m10, :text
    add_column :mentorats, :avatar_name_m1, :text
    add_column :mentorats, :avatar_name_m2, :text
    add_column :mentorats, :avatar_name_m3, :text
    add_column :mentorats, :avatar_name_m4, :text
    add_column :mentorats, :avatar_name_m5, :text
    add_column :mentorats, :avatar_name_m6, :text
    add_column :mentorats, :avatar_name_m7, :text
    add_column :mentorats, :avatar_name_m8, :text
    add_column :mentorats, :avatar_name_m9, :text
    add_column :mentorats, :avatar_name_m10, :text
    add_column :mentorats, :avatar_url_m1, :text
    add_column :mentorats, :avatar_url_m2, :text
    add_column :mentorats, :avatar_url_m3, :text
    add_column :mentorats, :avatar_url_m4, :text
    add_column :mentorats, :avatar_url_m5, :text
    add_column :mentorats, :avatar_url_m6, :text
    add_column :mentorats, :avatar_url_m7, :text
    add_column :mentorats, :avatar_url_m8, :text
    add_column :mentorats, :avatar_url_m9, :text
    add_column :mentorats, :avatar_url_m10, :text
    add_column :mentorats, :avatar_titre_m1, :text
    add_column :mentorats, :avatar_titre_m2, :text
    add_column :mentorats, :avatar_titre_m3, :text
    add_column :mentorats, :avatar_titre_m4, :text
    add_column :mentorats, :avatar_titre_m5, :text
    add_column :mentorats, :avatar_titre_m6, :text
    add_column :mentorats, :avatar_titre_m7, :text
    add_column :mentorats, :avatar_titre_m8, :text
    add_column :mentorats, :avatar_titre_m9, :text
    add_column :mentorats, :avatar_titre_m10, :text
    add_column :mentorats, :paraph_m1, :text
    add_column :mentorats, :paraph_m2, :text
    add_column :mentorats, :paraph_m3, :text
    add_column :mentorats, :paraph_m4, :text
    add_column :mentorats, :titre_m, :text
    add_column :mentorats, :sous_titre_m, :text
    add_column :mentorats, :date_m, :text
    add_column :mentorats, :lieu_m, :text
    add_column :mentorats, :lien_url1_m, :text
    add_column :mentorats, :lien_url2_m, :text
  end
end
